[workspace]
authors = ["Jack Tierney <jackcurragh@gmail.com>"]
channels = ["conda-forge"]
name = "RiboMetric"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
build = ">=1.3.0, <2"
twine = ">=6.2.0, <7"
textual = ">=0.47.0"
RiboMetric = { path = ".", editable = true }
