[workspace]
authors = ["Jack Tierney <jackcurragh@gmail.com>"]
channels = ["conda-forge"]
name = "RiboMetric"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
# Align with setup.py and CI (3.10â€“3.12)
python = ">=3.10,<3.13"

[pypi-dependencies]
build = ">=1.3.0, <2"
twine = ">=6.2.0, <7"
textual = ">=0.47.0"
RiboMetric = { path = ".", editable = true }
